// _app.js or RootLayout.js (depending on your Next.js setup)
import { Inter } from "next/font/google";
import "./globals.css";
// import CustomCursor from "@/components/showDot/CustomCursor";
import Navbar from "@/components/navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Footer } from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Navbar/>
        {children}
        {/* Ensure CustomCursor is included only once */}
       <Footer/>
        </body>
    </html>
  );
}
